name: 📦 Build & Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: 'Upload artifacts instead of creating a release'
        required: false
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DRY_RUN: ${{ github.event.inputs.dry_run }}

    steps:
      # Report the workflow configuration
      - name: Report configuration
        if: env.DRY_RUN == 'true'
        run: |
          echo "Dry Run!" >> $GITHUB_STEP_SUMMARY
          echo "Creating release version: ${{ env.tag }}" >> $GITHUB_STEP_SUMMARY

      # 1) Setup Go for the build script
      - name: Set up Go
        uses: actions/setup-go@main

      # 2) Clone the repository
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      # 3) Ensure your build script is runnable
      - name: Ensure executable scripts
        run: chmod +x scripts/*

      # 4) Run the build script
      - name: Build executables
        run: scripts/build.sh

      # 5*) Dry run: upload artifacts instead of releasing
      - name: Upload build artifacts (dry run)
        if: env.DRY_RUN == 'true'
        uses: actions/upload-artifact@main
        with:
          name: build-artifacts
          path: .bin/*

      # 5) Create a GitHub Release and upload files in .bin/
      - name: Create GitHub Release
        if: env.DRY_RUN != 'true'
        id: create_release
        uses: softprops/action-gh-release@master
        with:
          files: .bin/*
          generate_release_notes: true
          tag_name: ${{ env.tag }}

      # 6) Create release summary
      - name: Create job summary
        if: env.DRY_RUN != 'true'
        run: |
          echo "- Release: ${{ env.tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- Link: ${{ steps.create_release.outputs.url }}" >> $GITHUB_STEP_SUMMARY
