name: 📦 Build & Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: 'Upload artifacts instead of creating a release'
        required: false
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DRY_RUN: ${{ github.event.inputs.dry_run }}

    steps:
      - if: env.DRY_RUN == 'true'
        run: echo "::warning::Dry Run!"

      # 1) Clone the repository
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      # 2) Setup Go for the build script
      - name: Set up Go
        uses: actions/setup-go@main

      # 3) Run the build script
      - name: Build executables
        run: |
          chmod +x scripts/*
          scripts/build.sh build/chatgpt

      # 4*) Dry run: upload artifacts instead of releasing
      - name: Upload build artifacts (dry run)
        if: env.DRY_RUN == 'true'
        uses: actions/upload-artifact@main
        with:
          name: build-artifacts
          path: build/*

      # 4) Create a GitHub Release and upload build files
      - name: Create GitHub Release
        if: env.DRY_RUN != 'true'
        id: create_release
        uses: softprops/action-gh-release@master
        with:
          files: build/*
          generate_release_notes: true
          tag_name: ${{ github.ref_name }}

      - if: env.DRY_RUN != 'true'
        run: |
          echo "- Release: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- Link: ${{ steps.create_release.outputs.url }}" >> $GITHUB_STEP_SUMMARY
