name: Build & Release

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: "Upload artifacts without a release."
        required: false
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DEBUG: ${{ github.event.inputs.debug }}

    steps:
      - if: env.DEBUG == "true"
        run: echo "::warning::Debug mode is enabled."

      # 1) Clone the repository
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0 # shallow clone

      # 2) Set up Go for the build script
      - name: Set up Go
        uses: actions/setup-go@main

      # 3) Run the build scripts
      - name: Build executables
        run: |
          chmod +x scripts/*
          scripts/build.sh bin

      # 4) Debug: upload build files as artifacts
      - name: Upload build artifacts (dry run)
        if: env.DEBUG == "true" # for debugging only
        uses: actions/upload-artifact@main
        with:
          name: build-artifacts
          path: bin/*

      # 4) Release: create a release with build files
      - name: Create GitHub Release
        if: env.DEBUG != "true"
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ github.ref_name }}
          files: bin/*.zip
          generate_release_notes: true
